module.exports = disciplinas = [
    { cod: 1 ,name: ' distribuidos', description: 'Modelos de máquinas paralelas; Granularidade, níveis de paralelismo; Máquinas multiprocessadores e multi-computadores: topologia, arquiteturas fortemente acopladas e fracamente acopladas; Processos: threads, clientes, servidores, código móvel, agentes de software; Middlewares para aplicações distribuídas; Sincronização em sistemas distribuídos; Coordenação e acordo em sistemas distribuídos; Transações distribuídas: modelos, classificação e controle de concorrência; Tópicos de tolerância a falhas e segurança.'}, 
    { cod: 2 ,name: ' seguranca', description: 'Investigar as principais questões associadas à segurança de sistemas computacionais, bem como as técnicas e mecanismos usados para assegurar as propriedades de segurança; investigar os problemas de segurança computacional, bem como as técnicas e ferramentas disponíveis para mitigá-los. Proporcionar aos alunos conhecimentos em desenvolvimento de políticas de segurança e instalação, configuração e administração de produtos que auxiliem na manutenção dessas políticas.'}, 
    { cod: 3 ,name: ' metodologia', description: 'Fundamentos da metodologia científica; Normas e organização do texto científico (normas da ABNT/UTFPR); Preparação de um trabalho acadêmico; Métodos e técnicas de pesquisa; A comunicação entre orientadores e orientandos; A comunicação científica.'}, 
    { cod: 4 ,name: 'web ', description: 'Conceitos de desenvolvimento de aplicações para servidor Web. Desenvolvimento de aplicações Web em camadas.  Integração de aplicações Web com banco de dados. Linguagens de programação para Web. Frameworks para o desenvolvimento de aplicações Web.'}, 
    { cod: 5 ,name: 'rv ', description: 'Conceitos e aplicações de realidade virtual. Desenvolvimento de ambientes virtuais. Interação em ambientes virtuais. Sistemas de interfaces não convencionais. Realidade virtual imersiva e não imersiva. Arquitetura de sistemas de realidade virtual. Sistemas distribuídos de realidade virtual. Técnicas de modelagem e otimização de ambientes virtuais em sistemas de realidade virtual para plataformas de baixo custo. O padrão VRML97.'}, 
    { cod: 6 ,name: 'jogos', description: 'Ferramentas de desenvolvimento para jogos: visão geral e primeiros conceitos. Conhecendo o ambiente de desenvolvimento: Interface com o Usuário e Menus. Exemplos de uso (aplicação). Exploração de engine de desenvolvimento: Definição de Sprites, Sons, Música, Cenários e principais Objetos e Eventos. Definindo ações do jogo: controles, Pontuação e de arte. Assets. Jogabilidade (Game Play). Interação com o Jogador. Testando a build em dispositivos/hardware. Discussão jogos 2D e 3D: visão geral e conceitos. Ferramentas rápidas.'}, 
    { cod: 7 ,name: 'producao', description: ' Esta atividade tem como objetivo, compreender o problema, dando aos desenvolvedores e usuários, a mesma visão do que deve ser construído para resolução do problema. Desenvolvedores e clientes, em conjunto, buscam levantar e priorizar as necessidades dos futuros usuários do software (necessidades essas denominadas como requisitos)   O Levantamento de Requisitos é a etapa mais importante, no que diz respeito ao retorno de investimentos no projeto. Vários projetos são abandonados pelo baixo levantamento de requisitos, ou seja, membros da equipe não disponibilizaram tempo suficiente para essa fase do projeto, em compreender as necessidades dos clientes em relação ao sistema a ser desenvolvido    E como um sistema de informações geralmente é utilizado para automatizar processos de negócio em uma organização, esses processos da organização devem ser bem compreendidos para que o restante das atividades do processo de desenvolvimento flua de acordo com as reais necessidades do cliente '}, 
]

