module.exports = disciplinas = [
    { cod: 1 ,name: ' Sistemas Distribuidos ', description: 'Modelos de máquinas paralelas; Granularidade, níveis de paralelismo; Máquinas multiprocessadores e multi-computadores: topologia, arquiteturas fortemente acopladas e fracamente acopladas; Processos: threads, clientes, servidores, código móvel, agentes de software; Middlewares para aplicações distribuídas; Sincronização em sistemas distribuídos; Coordenação e acordo em sistemas distribuídos; Transações distribuídas: modelos, classificação e controle de concorrência; Tópicos de tolerância a falhas e segurança.'}, 
    { cod: 2 ,name: ' Seguranca e auditoria ', description: 'Investigar as principais questões associadas à segurança de sistemas computacionais, bem como as técnicas e mecanismos usados para assegurar as propriedades de segurança; investigar os problemas de segurança computacional, bem como as técnicas e ferramentas disponíveis para mitigá-los. Proporcionar aos alunos conhecimentos em desenvolvimento de políticas de segurança e instalação, configuração e administração de produtos que auxiliem na manutenção dessas políticas.'}, 
    { cod: 3 ,name: ' Metodologia de Pesquisa ', description: 'Fundamentos da metodologia científica; Normas e organização do texto científico (normas da ABNT/UTFPR); Preparação de um trabalho acadêmico; Métodos e técnicas de pesquisa; A comunicação entre orientadores e orientandos; A comunicação científica.'}, 
    { cod: 4 ,name: ' Programacao Web 2 ', description: 'Conceitos de desenvolvimento de aplicações para servidor Web. Desenvolvimento de aplicações Web em camadas.  Integração de aplicações Web com banco de dados. Linguagens de programação para Web. Frameworks para o desenvolvimento de aplicações Web.'}, 
    { cod: 5 ,name: ' Realidade Virtual ', description: 'Conceitos e aplicações de realidade virtual. Desenvolvimento de ambientes virtuais. Interação em ambientes virtuais. Sistemas de interfaces não convencionais. Realidade virtual imersiva e não imersiva. Arquitetura de sistemas de realidade virtual. Sistemas distribuídos de realidade virtual. Técnicas de modelagem e otimização de ambientes virtuais em sistemas de realidade virtual para plataformas de baixo custo. O padrão VRML97.'}, 
    { cod: 6 ,name: ' Desenvolvimento de Jogos ', description: 'Ferramentas de desenvolvimento para jogos: visão geral e primeiros conceitos. Conhecendo o ambiente de desenvolvimento: Interface com o Usuário e Menus. Exemplos de uso (aplicação). Exploração de engine de desenvolvimento: Definição de Sprites, Sons, Música, Cenários e principais Objetos e Eventos. Definindo ações do jogo: controles, Pontuação e de arte. Assets. Jogabilidade (Game Play). Interação com o Jogador. Testando a build em dispositivos/hardware. Discussão jogos 2D e 3D: visão geral e conceitos. Ferramentas rápidas.'}, 
    { cod: 7 ,name: ' Topicos em processos de Producao de Software', description: ''}, 
]

